org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official
kotlin.incremental=true

# AndroidShield publishing coordinates
androidshield.groupId=io.github.deepprojectgit.androidshield
androidshield.version=0.1.1
