package com.androidshield.core.crypto

import java.security.MessageDigest
import java.security.SecureRandom

/**
 * Scrambles a key for embedding in generated bytecode (XOR with a derived mask).
 * This is obfuscation, not standalone secrecy — combined with per-build randomness.
 */
object KeyScrambler {
    fun scramble(key: ByteArray, seed: ByteArray): ByteArray {
        val mask = deriveMask(seed, key.size)
        return ByteArray(
            key.size
        ) { index -> (key[index].toInt() xor mask[index].toInt()).toByte() }
    }

    fun unscramble(scrambled: ByteArray, seed: ByteArray): ByteArray = scramble(scrambled, seed)

    fun randomSeed(random: SecureRandom = SecureRandom()): ByteArray {
        val seed = ByteArray(16)
        random.nextBytes(seed)
        return seed
    }

    private fun deriveMask(seed: ByteArray, size: Int): ByteArray {
        val digest = MessageDigest.getInstance("SHA-256")
        val out = ByteArray(size)
        var produced = 0
        var counter = 0
        while (produced < size) {
            digest.reset()
            digest.update(seed)
            digest.update(counter.toByte())
            val block = digest.digest()
            val toCopy = minOf(block.size, size - produced)
            System.arraycopy(block, 0, out, produced, toCopy)
            produced += toCopy
            counter++
        }
        return out
    }
}
