package com.androidshield.plugin.r8

/**
 * Generates consumer/proguard keep and obfuscation assist rules for AndroidShield.
 */
object R8RulesGenerator {
    fun generate(
        protectPackages: List<String>,
        mappingProtection: Boolean,
    ): String = buildString {
        appendLine("# Generated by AndroidShield — do not edit")
        appendLine("-keep class com.androidshield.runtime.api.AndroidShield { *; }")
        appendLine("-keep class com.androidshield.runtime.crypto.** { *; }")
        appendLine("-keep class com.androidshield.core.model.** { *; }")
        appendLine("-keep class com.androidshield.core.config.** { *; }")
        appendLine("-keep class com.androidshield.core.integrity.** { *; }")
        appendLine("-keepclassmembers class * {")
        appendLine("    @com.androidshield.annotations.ShieldProtect *;")
        appendLine("    @com.androidshield.annotations.ShieldEncrypt *;")
        appendLine("}")
        protectPackages.forEach { pkg ->
            appendLine("-keep class $pkg.BuildShieldSecrets { *; }")
        }
        if (mappingProtection) {
            appendLine("# Discourage leaking mapping names for shield internals")
            appendLine("-repackageclasses 'o'")
            appendLine("-allowaccessmodification")
            appendLine("-overloadaggressively")
        }
        appendLine("-dontwarn com.androidshield.**")
    }
}
